apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: asia.gcr.io/go-exchange-staging/croc-hunter-jenkinsx
    context: .
  tagPolicy:
    envTemplate:
      template: 'bla/{{.ORG}}/croc-hunter-jenkinsx:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: 'bla/{{.ORG}}/croc-hunter-jenkinsx'
    local: {}
  deploy:
    helm:
      releases:
      - name: croc-hunter-jenkinsx
        chartPath: charts/croc-hunter-jenkinsx
        setValueTemplates:
          image.repository: 'bla/{{.ORG}}/croc-hunter-jenkinsx'
          image.tag: '{{.TAG}}'
