apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST}}:{{.JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT}}/{{.ORG}}/{{.APP_NAME}}:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    buildArgs:
      GIT_SHA: xxxx
      WORKFLOW_RELEASE: yyyy
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
