apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    kaniko:
      buildContext:
        localDir: {}
      cache: {}
  cluster:
    pullSecretName: kaniko-secret
    namespace: jx
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.ORG}}/croc-hunter-jenkinsx:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.ORG}}/croc-hunter-jenkinsx'
    local: {}
  deploy:
    helm:
      releases:
      - name: croc-hunter-jenkinsx
        chartPath: charts/croc-hunter-jenkinsx
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.ORG}}/croc-hunter-jenkinsx'
          image.tag: '{{.TAG}}'
