apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.ORG}}/croc-hunter-jenkinsx:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - image: changeme
      context: .
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.ORG}}/croc-hunter-jenkinsx'
    local: {}
  deploy:
    helm:
      releases:
      - name: croc-hunter-jenkinsx
        chartPath: charts/croc-hunter-jenkinsx
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.ORG}}/croc-hunter-jenkinsx'
          image.tag: '{{.TAG}}'
